### ISSUE TITLE
Missing uint16.tif in freetype-2.11.0?

### ISSUE THREAD

**Issue by ArchangeGabriel** [QuLogic/mpl-images#1]
Apparently under `matplotlib/test_image/` there should be `uint16.tif` ([upstream](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/tests/baseline_images/test_image/uint16.tif)). It’s present in some branches, but not in freetype-2.11.0. Is that expected?

P.S.: I’ve just discovered this repo because of breaking changes in our (Arch) testing during packaging, and while looking for a fix around baseline images I’ve discovered the corresponding discussion on the main repo and there a link pointing here.

**Comment by QuLogic** [comment]
That file does not have any text in it and is unaffected by FreeType. You need to overlay this repo on the existing test image set, so you have all the files.

**Comment by QuLogic** [comment]
This is annoying though, I might revert that while preparing 3.5.0 images.

**Comment by ArchangeGabriel** [comment]
Thanks for fixing this, I see you perfectly understood why it makes sense. ;)
