### ISSUE TITLE
Freetype 2.11.1 Tag

### ISSUE THREAD

**Issue by boomanaiden154** [QuLogic/mpl-images#2]
Freetype 2.11.1 ([see here](https://release-monitoring.org/project/854/) has been out for around a month and a number of current distros are currently on this version, including Fedora. Is it possible to get a new tag that lists the freetype version as 2.11.1? There don't seem to be any changes to 2.11.1 that change the images outputted by the matplotlib tests.

**Comment by QuLogic** [comment]
I don't usually tag if there are no changes required.

**Comment by boomanaiden154** [comment]
Sounds good. I should be able to work around it.
